# Eigenvalue and eigenvectors calculation

By definition, given a matrix $A$, we say that $\lambda \in \mathbb{C}$ is an _eigenvalue_ of $A$ if $\exist \mathbf{x} \neq 0$ such that $A \mathbf{x} = \lambda \mathbf{x}$. The vector $\mathbf{x}$ is called an eigenvector relative to $\lambda$. 

## Power iteration

- Find the largest eigenvalue $\lambda_{\max}$
\begin{align*}
\mathbf{q}_k & = \frac{\mathbf{z}_{k-1}}{\|\mathbf{z}_{k-1}\|_2}\\
\mathbf{z}_k & = A\mathbf{q}_{k}\\
\lambda_{\max}^k & = \mathbf{q}^T_k \mathbf{z}_k
\end{align*}

In [ ]:
import numpy as	np
import matplotlib.pyplot as plt

In [11]:
n = 9
h = 1./(n-1)

x=np.linspace(0,1,n)

a = -np.ones((n-1,))
b = 2*np.ones((n,))
A = (np.diag(a, -1) + np.diag(b, 0) + np.diag(a, +1))

A /= h**2

print(A)

[[128. -64.   0.   0.   0.   0.   0.   0.   0.]
 [-64. 128. -64.   0.   0.   0.   0.   0.   0.]
 [  0. -64. 128. -64.   0.   0.   0.   0.   0.]
 [  0.   0. -64. 128. -64.   0.   0.   0.   0.]
 [  0.   0.   0. -64. 128. -64.   0.   0.   0.]
 [  0.   0.   0.   0. -64. 128. -64.   0.   0.]
 [  0.   0.   0.   0.   0. -64. 128. -64.   0.]
 [  0.   0.   0.   0.   0.   0. -64. 128. -64.]
 [  0.   0.   0.   0.   0.   0.   0. -64. 128.]]


In [ ]:


def PM(A,z0=None,tol=1e-5,nmax=500):
	"""
	Power method for the computation of the largest eigenvalue of a matrix A
	"""
	
	n,m = A.shape
	assert n == m, "Matrix must be square"
	
	if z0 is None:
		z0 = np.ones(n)
		
	q = z0/np.linalg.norm(z0,2) # normalize initial guess
	it = 0
	err = tol + 1.
	while it < nmax and err > tol:
		z = A@q # iteration
		l = q.T@z 
		q = z/np.linalg.norm(z,2)
		err = np.linalg.norm(z-l*q,2)
		
		it += 1

	return l,q,it

l,x,power_iter_count = PM(A)

print(f"Largest eigenvalue: {l}, found in {power_iter_count} iterations")
print(f"Numpy largest eigenvalue: {np.linalg.eig(A)[0].max()}")



Largest eigenvalue: 249.7351578756851, found in 39 iterations
Numpy largest eigenvalue: 249.7352340857797


## Inverse power method
- Find the eigenvalue $\lambda$ **closest** to $\mu$
\begin{align}
M & = A-\mu I\\
& \\
M\mathbf{x}_k &= \mathbf q_{k-1}\\
\mathbf{q}_k & = \frac{\mathbf{x}_k}{\|\mathbf{x}_k\|_2}\\
\mathbf{z}_k & = A\mathbf{q}_{k}\\
\lambda^k & = \mathbf{q}^T_k \mathbf{z}_k
\end{align}


In [ ]:
def IPM(A, z0=None, mu=0, tol=1e-5, nmax=500):
	"""
	Inverse Power Method for the computation of the eigenvalue of a matrix A closest to mu
	"""
	


In [32]:
l,x,inverse_power_iter_count = IPM(A, mu=60)
print(f"Eigenvalue: {l}, found in {inverse_power_iter_count} iterations")


Eigenvalue: 52.76348770656334, found in 9 iterations
